server:
  port: 8081
spring:
  application:
    name: personalinfo-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/TEST
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver